version: "3.7"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ES_INDEX=es
    depends_on:
      - es
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - net0

  es:
    image: elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
    ports:
      - "9200:9200"
    networks:
      - net0
    volumes:
      - es_data:/usr/share/elasticsearch/data  # Optional for persistent data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  net0:
    driver: bridge

volumes:
  es_data:
