version: "3.7"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ES_INDEX=es
    depends_on:
      - es
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - net0

  es:
    image: elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
    ports:
      - "9200:9200"
    networks:
      - net0

networks:
  net0:
    driver: bridge
