version: "3.7"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - es
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - net0

  es:
    image: elasticsearch:7.3.0
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://localhost:9000
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
    ports:
      - "9200:9200"
    networks:
      - net0

networks:
  net0:
    driver: bridge
