// For Nuxt 3
import { library, config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

/* import specific icons */
import {
  faCircle,
  faEye,
  faCode,
  faSyncAlt,
  faTrash,
  faBolt,
  faLock,
  faLockOpen,
  faStepBackward,
  faStepForward,
  faChevronRight,
  faExternalLinkAlt,
  faEnvelope,
  faCogs,
  faListOl,
  faTasks,
  faLightbulb,
  faPlus,
  faClipboard,
  faChevronLeft,
  faCheck,
  faCodeBranch,
  faSearch,
  faArrowRight,
  faUser,
  faBuilding,
  faTimes,
  faUndo,
  faSpinner,
  faMinusSquare,
  faPlusSquare,
  faHome,
  faNotEqual,
  faListUl,
  faDotCircle,
  faFileDownload,
  faExclamationCircle,
  faRegistered,
  faRetweet,
  faAsterisk,
  faSquare,
  faCaretRight,
  faTimesCircle,
  faFileMedical,
  faUserCheck,
  faSignInAlt,
  faPenSquare,
  faQuestionCircle,
  faStar,
  faInfoCircle,
  faMinusCircle,
  faCheckCircle,
  faEllipsisH,
  faMinus,
  faFileImport,
  faLink,
  faCalendarAlt,
  faHashtag,
  faCog,
  faChevronDown,
  faChevronUp,
} from "@fortawesome/free-solid-svg-icons";
import {
  faGithub,
  faGithubAlt,
  faGoogle,
} from "@fortawesome/free-brands-svg-icons";

// You can add your icons directly in this plugin. See other examples for how you
// can add other styles or just individual icons.
library.add(
  faGithub,
  faCircle,
  faEye,
  faCode,
  faSyncAlt,
  faTrash,
  faBolt,
  faLock,
  faLockOpen,
  faStepBackward,
  faStepForward,
  faChevronRight,
  faExternalLinkAlt,
  faEnvelope,
  faCogs,
  faListOl,
  faListUl,
  faTasks,
  faLightbulb,
  faPlus,
  faClipboard,
  faChevronLeft,
  faCheck,
  faCodeBranch,
  faSearch,
  faArrowRight,
  faUser,
  faBuilding,
  faTimes,
  faUndo,
  faSpinner,
  faMinusSquare,
  faPlusSquare,
  faHome,
  faNotEqual,
  faDotCircle,
  faFileDownload,
  faExclamationCircle,
  faRegistered,
  faRetweet,
  faAsterisk,
  faSquare,
  faCaretRight,
  faTimesCircle,
  faGithubAlt,
  faFileMedical,
  faUserCheck,
  faSignInAlt,
  faPenSquare,
  faQuestionCircle,
  faStar,
  faInfoCircle,
  faTimesCircle,
  faMinusCircle,
  faCheckCircle,
  faEllipsisH,
  faMinus,
  faTimesCircle,
  faFileImport,
  faLink,
  faCalendarAlt,
  faHashtag,
  faGoogle,
  faCog,
  faChevronDown,
  faChevronUp
);

// This is important, we are going to let Nuxt worry about the CSS
config.autoAddCss = false;

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("font-awesome-icon", FontAwesomeIcon, {});
});
